package com.data.model;


import org.springframework.context.annotation.Profile;

import javax.persistence.*;

@Entity
@Table(name = "strings")
public class Strings {
    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private long id;

    private String name;

    private String de;

    private String en;


    public long getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getDe() {
        return de;
    }

    public String getEn(){ return en;}
}
